### ISSUE TITLE
Add column to NBA gamelogs indicating season type

### ISSUE THREAD

**Issue by jimtheflash** [jimtheflash/gambling_stuff#10]
Add a column to NBA season gamelogs to indicate season type, i.e. preseason, regular, playoffs. Not sure the easiest way to do this! fwiw though the data that currently exists as of the creation of this issue is all regular season.

**Comment by johnlovesdata** [comment]
I can take this. Thinking we can add a column: `SEASON_TYPE` that's one of 
- Pre Season
- Regular Season
- Playoffs

These values align with the descriptions here: [SeasonType](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/library/parameters.md#SeasonType)

Then it's pretty easy to backfill this value on the current files
